---
- name: Install needed packages
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
  when: "'metastore' in group_names"

- name: Install mysql server
  yum:
    name: mysql-server
  when: "'metastore' in group_names"

- name: Install YUM required software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-devel
    - "@Development tools"
    - mysql-community-devel
    - mysql-connector-java*
  when: "'metastore' in group_names"

- name: Install PIP required software
  pip:
    name: "{{ item }}"
    state: forcereinstall
  with_items:
    - pip
    - MySQL-python
  when: "'metastore' in group_names"

- name: reload systemctl
  systemd:
    daemon_reload: yes
  when: "'metastore' in group_names"

- name: Install mysql-server on boot and ensure started
  systemd:
    name: mysqld
    state: started
    enabled: yes
  when: "'metastore' in group_names"

- name: Debug password
  debug:
    msg: "{{ hive_metastore_password }}"

- name: Add mysql hive user
  mysql_user:
    login_user: "{{ mysql_admin_login | default('root') }}"
    login_password: "{{ mysql_admin_password | default('') }}"
    login_host: "{{ hive_metastore_url | default('localhost') }}"
    name: "{{ hive_metastore_user }}"
    password: "{{ hive_metastore_password }}"
    host: "{{ hive_metastore_host | default('%') }}"
    priv: "*.*:ALL"
    state: present
  when: "'metastore' in group_names"

- name: Copy mysql connector to hive lib folder
  copy:
    remote_src: yes
    src: /usr/share/java/mysql-connector-java.jar
    dest: /usr/hdp/current/hive-client/lib
    owner: "{{ hive_user | default('hive') }}"
    group: "{{ hadoop_group | default('hadoop') }}"
    mode: 0644
  when: "'metastore' in group_names"

- name: Create mysql metastore database
  mysql_db:
    login_user: "{{ mysql_admin_login | default('root') }}"
    login_password: "{{ mysql_admin_password | default('') }}"
    login_host: "{{ hive_metastore_url | default('localhost') }}"
    name: metastore_db
    state: present