---
- name: Format HDFS NameNode
  shell: /usr/hdp/current/hadoop-hdfs-namenode/../hadoop/bin/hdfs namenode -format -force
  become: true
  become_user: hdfs
  when: "'name_node' in group_names"
  ignore_errors: yes

- name: Create HDFS NameNode Service
  template:
    src: hadoop-name-node.service.j2
    dest: /usr/lib/systemd/system/hadoop-name-node.service
    owner: root
    group: root
    mode: 644
  when: "'name_node' in group_names"

- name: Create HDFS SecondaryNameNode Service
  template:
    src: hadoop-seconday-name-node.service.j2
    dest: /usr/lib/systemd/system/hadoop-secondary-name-node.service
    owner: root
    group: root
    mode: 644
  when: "'secondary_name_node' in group_names"

- name: Create HDFS DataNode Service
  template:
    src: hadoop-data-node.service.j2
    dest: /usr/lib/systemd/system/hadoop-data-node.service
    owner: root
    group: root
    mode: 644
  when: "'data_nodes' in group_names"

- name: Force systemd to reload configs
  systemd:
    daemon_reload: yes

- name: Start HDFS NameNode Service
  systemd:
    name: hadoop-name-node
    state: started
    enabled: yes
  when: "'name_node' in group_names"

- name: Start HDFS SecondaryNameNode Service
  systemd:
    name: hadoop-seconday-name-node
    state: started
    enabled: yes
  when: "'secondary_name_node' in group_names"

- name: Start HDFS DataNode Service
  systemd:
    name: hadoop-data-node
    state: started
    enabled: yes
  when: "'data_nodes' in group_names"

- name: Create HDFS mapreduce directory
  shell: hdfs dfs -mkdir -p /hdp/apps/mapreduce/
  become: yes
  become_user: "{{ hdfs_user }}"
  when: "'name_node' in group_names"

- name: Put mapreduce tarball in HDFS
  shell: hdfs dfs -put /usr/hdp/current/hadoop-client/mapreduce.tar.gz /hdp/apps/{{ hdp_version }}/mapreduce/
  become: yes
  become_user: "{{ hdfs_user }}"
  when: "'name_node' in group_names"

- name: Change HDP directory owner permission
  shell: hdfs dfs -chown -R {{ hdfs_user }}:{{ hadoop_group }} /hdp
  become: yes
  become_user: "{{ hdfs_user }}"
  when: "'name_node' in group_names"

- name: Change mapreduce directory mode
  shell: hdfs dfs -chmod -R 555 /hdp/apps/{{ hdp_version }}/mapreduce
  become: yes
  become_user: "{{ hdfs_user }}"
  when: "'name_node' in group_names"

- name: Change mapreduce tarball mode
  shell: hdfs dfs -chmod 444 /hdp/apps/<hdp_version>/mapreduce/mapreduce.tar.gz
  become: yes
  become_user: "{{ hdfs_user }}" 
  when: "'name_node' in group_names"

- name: Create YARN resourcemanager Service
  template:
    src: hadoop-yarn-resourcemanager.service.j2
    dest: /usr/lib/systemd/system/hadoop-yarn-resourcemanager.service
    owner: root
    group: root
    mode: 644
  when: "'resource_manager' in group_names"

- name: Create YARN nodemanager Service
  template:
    src: hadoop-yarn-nodemanager.service.j2
    dest: /usr/lib/systemd/system/hadoop-yarn-nodemanager.service
    owner: root
    group: root
    mode: 644
  when: "'resource_manager' not in group_names"