---
- name: Set umask
  lineinfile:
    path: /etc/profile
    insertafter: EOF
    line: umask 0022

- name: Install Hadoop packages
  yum:
    name: hadoop, hadoop-hdfs, hadoop-libhdfs, hadoop-yarn, hadoop-mapreduce, hadoop-client, openssl
    update_cache: yes
    state: latest

- name: Install Snappy compression library
  yum:
    name: snappy, snappy-devel
    update_cache: yes
    state: latest

- name: Install LZO compression library
  yum:
    name: lzo, lzo-devel, hadooplzo, hadooplzo-native
    update_cache: yes
    state: latest

- name: Copy environment file to profile
  template:
    src: hadoop_env.sh.j2
    dest: /etc/profile.d
    owner: root
    group: root
    mode: 0644

- import_tasks: setup-hdfs-directories.yml

- import_tasks: setup-yarn-directories.yml

- import_tasks: setup-mapreduce-directories.yml

- name: Find HDP version
  yum:
    list: hdp-select
    state: installed
  register: hdp_version
  
- name: Symlink Directories with hdp-select
  shell: hdp-select set all {{ hdp_version.results[1].version }}-{{ hdp_version.results[1].release }}

- import_tasks: configure.yml

- import_tasks: create-systemd-services.yml