# - hosts: all
#   become: yes
#   roles:
#     - hdp-commons
# 
# - hosts: zookeeper
#   become: yes
#   roles:
#     - zookeeper
# 
# - hosts: hadoop
#   become: yes
#   roles:
#     - hadoop

- hosts: client_nodes
  become: yes
  roles:
    - hive