- hosts: all
  become: yes

  tasks:

  - name: Download Ambari Repository
    get_url:
      url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.1.0/ambari.repo 
      dest: /etc/yum.repos.d/ambari.repo

  - name: Install Ambari Server
    yum:
      name: ambari-server
      update_cache: yes
      state: latest

  - name: Setup ambari-server
    command: ambari-server setup -s

  - name: Start ambari-server
    command: ambari-server start
    ignore_errors: yes

