- hosts: all
  become: yes

  tasks:

  - name: Install EPEL Repository
    yum:
      name: epel-release
      update_cache: yes
      state: latest

  - name: Install NTP
    yum:
      name: ntp
      update_cache: yes
      state: latest

  - name: Start NTP service
    systemd:
      name: ntpd
      state: started
      enabled: yes

  - name: Disable SELINUX
    selinux:
      state: disabled

  - name: Disable firewall service
    systemd:
      name: firewalld
      state: stopped
      enabled: no

  - name: Fix /etc/hosts to remove .local
    lineinfile:
      path: /etc/hosts
      regexp: "^(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+(.*?)\\.local\\s+\\2"
      backrefs: yes
      line: "\\1\\t\\2"

  - name: Add node names to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "{{ item.ip }} {{ item.fqdn }}"
      state: present
    with_items: "{{ domain_names }}"
