---
- name: Download Java 8
  command: "wget -q -O '/tmp/jdk-{{java_version}}.rpm' --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{java_download_url}}"

- name: Install Java
  yum:
    name: /tmp/jdk-{{java_version}}.rpm
    state: present

- name: Set JAVA_HOME
  copy:
    src: java_home.sh
    dest: /etc/profile.d/java_home.sh
    owner: root
    group: root
    mode: 0644
