---
# Tasks lists divided following HortonWorks documentation (https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.4/bk_command-line-installation/content/ch_getting_ready_chapter.html)
- import_tasks: system-requirements.yml

- import_tasks: jdk-requirements.yml

- include_tasks: metastore-requirements.yml
  when: "'metastore_server' in group_names"

- import_tasks: remote-repositories.yml

- import_tasks: environment-preparing.yml

- name: Disable firewall service
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Fix /etc/hosts to remove .local
  lineinfile:
    path: /etc/hosts
    regexp: "^(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+(.*?)\\.local\\.vagrant\\.test\\s+\\2"
    backrefs: yes
    line: "\\1\\t\\2"