---
# Tasks lists divided following HortonWorks documentation (https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.4/bk_command-line-installation/content/ch_getting_ready_chapter.html)
- import_tasks: system-requirements.yml

- import_tasks: jdk-requirements.yml

- include_tasks: metastore-requirements.yml
  when: "'metastore_server' in group_names"

- import_tasks: remote-repositories.yml

- import_tasks: environment-preparing.yml
