---
# the directory where ZooKeeper is installed
zookeeper_home_dir: /usr/hdp/current/zookeeper-server

# the directory to store the ZooKeeper configuration files
zookeeper_conf_dir: "{{ zookeeper_home_dir }}/conf"

# the zookeeper "directory" to stor zookeeper server pid
zookeeper_pid_dir: /var/run/zookeeper/zookeeper_server.pid

# the directory to store the ZooKeeper data files
zookeeper_data_dir: /grid/hadoop/zookeeper/data

# the directory to store the ZooKeeper logs
zookeeper_log_dir: /var/log/zookeeper

# the user owning the ZooKeeper services
zookeeper_user: zookeeper

# the user's password owning the ZooKeeper services
zookeeper_password: zookeeper

# The number of milliseconds of each tick
zookeeper_tick_time: 2000

# The number of ticks that the initial synchronization phase can take
zookeeper_init_limit: 10

# the port at which the clients will connect
zookeeper_client_port: 2181

# name of the hadoop global group
hadoop_group: hadoop

# {{ zookeeper_conf_dir }}/myid placeholder
zookeeper_data_dir_myid: 1

# Zookeepers hosts to set on cfg.zoo
zookeeper_cluster_hosts:
  zookeeper-1.local.vagrant.test: 1
  zookeeper-2.local.vagrant.test: 2
  zookeeper-3.local.vagrant.test: 3